#!/usr/bin/env python3
"""Regenerate docs/bibtex-keys-list.md from _bibliography/references.bib.

The list is a lookup aid: every key with enough metadata to recognise the work.
It is generated, never hand-edited -- a hand-maintained copy drifts, and the one
this replaced was 32 entries behind with braces leaking into titles and authors.

    python scripts/gen_bibtex_keys.py [--check]

--check exits 1 if the committed file is out of date, for CI.
"""
import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
BIB = ROOT / '_bibliography' / 'references.bib'
OUT = ROOT / 'docs' / 'bibtex-keys-list.md'

# LaTeX accent forms Zotero emits, e.g. {\^a} {\'u} {\c c} {\"o} {\~n}
ACCENTS = {
    ('^', 'a'): 'â', ('^', 'e'): 'ê', ('^', 'i'): 'î', ('^', 'o'): 'ô', ('^', 'u'): 'û',
    ("'", 'a'): 'á', ("'", 'e'): 'é', ("'", 'i'): 'í', ("'", 'o'): 'ó', ("'", 'u'): 'ú',
    ("'", 'c'): 'ć', ("'", 'n'): 'ń', ("'", 's'): 'ś', ("'", 'z'): 'ź',
    ('`', 'a'): 'à', ('`', 'e'): 'è', ('`', 'i'): 'ì', ('`', 'o'): 'ò', ('`', 'u'): 'ù',
    ('"', 'a'): 'ä', ('"', 'e'): 'ë', ('"', 'i'): 'ï', ('"', 'o'): 'ö', ('"', 'u'): 'ü',
    ('~', 'a'): 'ã', ('~', 'n'): 'ñ', ('~', 'o'): 'õ',
    ('c', 'c'): 'ç', ('c', 's'): 'ş', ('v', 'c'): 'č', ('v', 's'): 'š', ('v', 'z'): 'ž',
    ('=', 'a'): 'ā', ('=', 'e'): 'ē', ('=', 'i'): 'ī', ('=', 'o'): 'ō', ('=', 'u'): 'ū',
}


def parse_entries(text):
    """Yield (entry_type, key, {field: raw_value}) for each @entry in the file."""
    for m in re.finditer(r'@(\w+)\s*\{\s*([^,\s]+)\s*,', text):
        etype, key = m.group(1).lower(), m.group(2)
        if etype in ('comment', 'string', 'preamble'):
            continue
        yield etype, key, parse_fields(text, m.end())


def parse_fields(text, i):
    """Parse `name = value,` pairs from i until the entry's closing brace."""
    fields, n = {}, len(text)
    while i < n:
        while i < n and text[i] in ' \t\r\n,':
            i += 1
        if i >= n or text[i] == '}':
            break
        m = re.match(r'([A-Za-z][\w-]*)\s*=\s*', text[i:])
        if not m:                                  # unparseable -- skip to next comma
            j = text.find(',', i)
            if j < 0:
                break
            i = j + 1
            continue
        name = m.group(1).lower()
        i += m.end()
        if text[i] == '{':
            depth, start = 0, i
            while i < n:
                if text[i] == '{':
                    depth += 1
                elif text[i] == '}':
                    depth -= 1
                    if depth == 0:
                        i += 1
                        break
                i += 1
            fields[name] = text[start + 1:i - 1]
        elif text[i] == '"':
            start = i + 1
            i = text.find('"', start)
            fields[name] = text[start:i]
            i += 1
        else:
            m2 = re.match(r'[^,}]*', text[i:])
            fields[name] = m2.group(0).strip()
            i += m2.end()
    return fields


def clean(v):
    """Render a raw BibTeX value as plain text: accents, then braces removed."""
    if not v:
        return ''
    v = re.sub(r'\s+', ' ', v).strip()
    v = re.sub(r'\{\\([\^\'`"~=cv])\s*\{?([a-zA-Z])\}?\}',
               lambda m: ACCENTS.get((m.group(1), m.group(2)), m.group(2)), v)
    v = re.sub(r'\\([\^\'`"~=cv])\{([a-zA-Z])\}',
               lambda m: ACCENTS.get((m.group(1), m.group(2)), m.group(2)), v)
    v = v.replace(r'\&', '&').replace(r'\%', '%').replace(r'\_', '_').replace(r'\$', '$')
    v = re.sub(r'\\(emph|textit|textbf|textsc)\s*\{(.*?)\}', r'\2', v)
    v = re.sub(r'\{\\copyright\}', '(c)', v)
    v = v.replace('{', '').replace('}', '')        # case-protection braces
    return re.sub(r'\s+', ' ', v).strip()


def year_of(f):
    raw = f.get('year') or f.get('date') or ''
    m = re.search(r'\b(1[89]\d\d|20\d\d)\b', raw)
    return m.group(1) if m else 'n.d.'


def render(entries):
    out = ['# All BibTeX Keys in references.bib', '',
           f'**Total entries:** {len(entries)}', '',
           '_Generated by `scripts/gen_bibtex_keys.py` -- do not edit by hand._', '',
           '_Use Cmd+F (Mac) or Ctrl+F (Windows) to search by title or author._', '', '---', '']
    for etype, key, f in entries:
        out.append(f'### `{key}`')
        out.append('')
        out.append(f'- **Type:** {etype}')
        title = clean(f.get('title') or f.get('shorttitle') or '')
        if title:
            out.append(f'- **Title:** {title}')
        who = clean(f.get('author') or f.get('editor') or '')
        if who:
            label = 'Author' if f.get('author') else 'Editor'
            out.append(f'- **{label}:** {who}')
        out.append(f'- **Year:** {year_of(f)}')
        for name, label in (('journal', 'Journal'), ('journaltitle', 'Journal'),
                            ('booktitle', 'In'), ('publisher', 'Publisher'),
                            ('institution', 'Institution')):
            if f.get(name):
                out.append(f'- **{label}:** {clean(f[name])}')
                break
        if f.get('doi'):
            out.append(f'- **DOI:** {clean(f["doi"])}')
        elif f.get('url'):
            out.append(f'- **URL:** {clean(f["url"])}')
        out.append('')
    return '\n'.join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true',
                    help='exit 1 if the committed file is out of date')
    args = ap.parse_args()

    entries = sorted(parse_entries(BIB.read_text(encoding='utf-8')),
                     key=lambda e: e[1].lower())
    keys = [e[1] for e in entries]
    dupes = {k for k in keys if keys.count(k) > 1}
    if dupes:
        print(f'DUPLICATE KEYS in references.bib: {sorted(dupes)}', file=sys.stderr)
        return 1

    new = render(entries)
    old = OUT.read_text(encoding='utf-8') if OUT.exists() else ''
    if args.check:
        if new != old:
            print(f'{OUT.relative_to(ROOT)} is out of date -- '
                  f'run: python scripts/gen_bibtex_keys.py', file=sys.stderr)
            return 1
        print(f'up to date ({len(entries)} entries)')
        return 0

    OUT.write_text(new, encoding='utf-8')
    print(f'wrote {OUT.relative_to(ROOT)}: {len(entries)} entries'
          f'{"" if new != old else " (unchanged)"}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
